// GENERATED by tool/build_icons.dart from Material Symbols Rounded
// (737e3324305806514d7909874fa1818ae1808232). Edit the list there and rerun it.

import 'package:flutter/widgets.dart';

/// Material Symbols Rounded, the only icon family the app uses.
abstract final class OcIcons {
  static const String fontFamily = 'MaterialSymbolsRounded';

  static const IconData accountCircle = IconData(
    0xf20b,
    fontFamily: fontFamily,
  );
  static const IconData add = IconData(0xe145, fontFamily: fontFamily);
  static const IconData addReaction = IconData(0xe1d3, fontFamily: fontFamily);
  static const IconData alternateEmail = IconData(
    0xe0e6,
    fontFamily: fontFamily,
  );
  static const IconData arrowBack = IconData(0xe5c4, fontFamily: fontFamily);
  static const IconData arrowDownward = IconData(
    0xe5db,
    fontFamily: fontFamily,
  );
  static const IconData arrowDropDown = IconData(
    0xe5c5,
    fontFamily: fontFamily,
  );
  static const IconData attachFile = IconData(0xe226, fontFamily: fontFamily);
  static const IconData badge = IconData(0xea67, fontFamily: fontFamily);
  static const IconData block = IconData(0xf08c, fontFamily: fontFamily);
  static const IconData bugReport = IconData(0xe868, fontFamily: fontFamily);
  static const IconData callEnd = IconData(0xf0bc, fontFamily: fontFamily);
  static const IconData campaign = IconData(0xef49, fontFamily: fontFamily);
  static const IconData check = IconData(0xe668, fontFamily: fontFamily);
  static const IconData checkBox = IconData(0xe9de, fontFamily: fontFamily);
  static const IconData checkBoxOutlineBlank = IconData(
    0xe835,
    fontFamily: fontFamily,
  );
  static const IconData chevronRight = IconData(0xe5cc, fontFamily: fontFamily);
  static const IconData close = IconData(0xe5cd, fontFamily: fontFamily);
  static const IconData closeFullscreen = IconData(
    0xf1cf,
    fontFamily: fontFamily,
  );
  static const IconData cloudOff = IconData(0xe2c1, fontFamily: fontFamily);
  static const IconData code = IconData(0xe86f, fontFamily: fontFamily);
  static const IconData contentCopy = IconData(0xe14d, fontFamily: fontFamily);
  static const IconData contrast = IconData(0xeb37, fontFamily: fontFamily);
  static const IconData createNewFolder = IconData(
    0xe2cc,
    fontFamily: fontFamily,
  );
  static const IconData darkMode = IconData(0xe51c, fontFamily: fontFamily);
  static const IconData dashboard = IconData(0xe871, fontFamily: fontFamily);
  static const IconData delete = IconData(0xe92e, fontFamily: fontFamily);
  static const IconData desktopWindows = IconData(
    0xe30c,
    fontFamily: fontFamily,
  );
  static const IconData dns = IconData(0xe875, fontFamily: fontFamily);
  static const IconData doneAll = IconData(0xe877, fontFamily: fontFamily);
  static const IconData download = IconData(0xf090, fontFamily: fontFamily);
  static const IconData dragIndicator = IconData(
    0xe945,
    fontFamily: fontFamily,
  );
  static const IconData edit = IconData(0xf097, fontFamily: fontFamily);
  static const IconData error = IconData(0xf8b6, fontFamily: fontFamily);
  static const IconData expandLess = IconData(0xe5ce, fontFamily: fontFamily);
  static const IconData expandMore = IconData(0xe5cf, fontFamily: fontFamily);
  static const IconData fingerprint = IconData(0xe90d, fontFamily: fontFamily);
  static const IconData forum = IconData(0xe8af, fontFamily: fontFamily);
  static const IconData gavel = IconData(0xe90e, fontFamily: fontFamily);
  static const IconData graphicEq = IconData(0xe1b8, fontFamily: fontFamily);
  static const IconData group = IconData(0xea21, fontFamily: fontFamily);
  static const IconData headphones = IconData(0xf01f, fontFamily: fontFamily);
  static const IconData headsetOff = IconData(0xe33a, fontFamily: fontFamily);
  static const IconData hourglassEmpty = IconData(
    0xe88b,
    fontFamily: fontFamily,
  );
  static const IconData info = IconData(0xe88e, fontFamily: fontFamily);
  static const IconData key = IconData(0xe73c, fontFamily: fontFamily);
  static const IconData keyboard = IconData(0xe312, fontFamily: fontFamily);
  static const IconData keyboardArrowDown = IconData(
    0xe313,
    fontFamily: fontFamily,
  );
  static const IconData lightMode = IconData(0xe518, fontFamily: fontFamily);
  static const IconData link = IconData(0xe250, fontFamily: fontFamily);
  static const IconData lock = IconData(0xe899, fontFamily: fontFamily);
  static const IconData logout = IconData(0xe9ba, fontFamily: fontFamily);
  static const IconData mail = IconData(0xe159, fontFamily: fontFamily);
  static const IconData markChatRead = IconData(0xf18b, fontFamily: fontFamily);
  static const IconData menu = IconData(0xe5d2, fontFamily: fontFamily);
  static const IconData mic = IconData(0xe31d, fontFamily: fontFamily);
  static const IconData micOff = IconData(0xe02b, fontFamily: fontFamily);
  static const IconData monitor = IconData(0xef5b, fontFamily: fontFamily);
  static const IconData mood = IconData(0xea22, fontFamily: fontFamily);
  static const IconData moreHoriz = IconData(0xe5d3, fontFamily: fontFamily);
  static const IconData moreVert = IconData(0xe5d4, fontFamily: fontFamily);
  static const IconData notifications = IconData(
    0xe7f5,
    fontFamily: fontFamily,
  );
  static const IconData notificationsOff = IconData(
    0xe7f6,
    fontFamily: fontFamily,
  );
  static const IconData openInFull = IconData(0xf1ce, fontFamily: fontFamily);
  static const IconData openInNew = IconData(0xe89e, fontFamily: fontFamily);
  static const IconData palette = IconData(0xe40a, fontFamily: fontFamily);
  static const IconData person = IconData(0xf0d3, fontFamily: fontFamily);
  static const IconData personAdd = IconData(0xea4d, fontFamily: fontFamily);
  static const IconData personRemove = IconData(0xef66, fontFamily: fontFamily);
  static const IconData pushPin = IconData(0xf10d, fontFamily: fontFamily);
  static const IconData refresh = IconData(0xe5d5, fontFamily: fontFamily);
  static const IconData reply = IconData(0xe15e, fontFamily: fontFamily);
  static const IconData schedule = IconData(0xefd6, fontFamily: fontFamily);
  static const IconData screenShare = IconData(0xe0e2, fontFamily: fontFamily);
  static const IconData search = IconData(0xef7a, fontFamily: fontFamily);
  static const IconData send = IconData(0xe163, fontFamily: fontFamily);
  static const IconData settings = IconData(0xe8b8, fontFamily: fontFamily);
  static const IconData shieldPerson = IconData(0xf650, fontFamily: fontFamily);
  static const IconData star = IconData(0xf09a, fontFamily: fontFamily);
  static const IconData stopScreenShare = IconData(
    0xe0e3,
    fontFamily: fontFamily,
  );
  static const IconData sync = IconData(0xe627, fontFamily: fontFamily);
  static const IconData tag = IconData(0xe9ef, fontFamily: fontFamily);
  static const IconData tune = IconData(0xe429, fontFamily: fontFamily);
  static const IconData upload = IconData(0xf09b, fontFamily: fontFamily);
  static const IconData verifiedUser = IconData(0xf013, fontFamily: fontFamily);
  static const IconData videocam = IconData(0xe04b, fontFamily: fontFamily);
  static const IconData videocamOff = IconData(0xe04c, fontFamily: fontFamily);
  static const IconData visibility = IconData(0xe8f4, fontFamily: fontFamily);
  static const IconData visibilityOff = IconData(
    0xe8f5,
    fontFamily: fontFamily,
  );
  static const IconData volumeOff = IconData(0xe04f, fontFamily: fontFamily);
  static const IconData volumeUp = IconData(0xe050, fontFamily: fontFamily);
  static const IconData warning = IconData(0xf083, fontFamily: fontFamily);
  static const IconData webAsset = IconData(0xe069, fontFamily: fontFamily);
}
