[package]
name = "opencord-proto"
description = "Protobuf types for the Opencord gateway protocol."
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "MPL-2.0"
publish = false

[dependencies]
prost.workspace = true

[build-dependencies]
prost-build.workspace = true
