[package]
name = "opencord-common"
description = "Building blocks shared by the Opencord server and client core."
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "MPL-2.0"
publish = false

[dependencies]
bitflags.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
thiserror.workspace = true
