// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `client`, `deliver`, `identity_info`, `invalid_input`, `lock_events`, `on_runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Events`

/// Opens local data in `app_data_dir`. Safe to call again (for example
/// after a hot restart); later calls do nothing.
void init({required String appDataDir}) =>
    RustLib.instance.api.crateApiClientInit(appDataDir: appDataDir);

/// Every event from every server, in order. Opening it again replaces the
/// previous stream.
Stream<CoreEvent> eventStream() =>
    RustLib.instance.api.crateApiClientEventStream();

GeneratedIdentity identityGenerate() =>
    RustLib.instance.api.crateApiClientIdentityGenerate();

/// Uses this identity and display name for every server, and connects to
/// the saved servers.
IdentityInfo identityLoad({
  required List<int> secret,
  required String displayName,
}) => RustLib.instance.api.crateApiClientIdentityLoad(
  secret: secret,
  displayName: displayName,
);

/// Text for an identity backup file. It contains the secret key.
String identityBackupEncode({required List<int> secret}) =>
    RustLib.instance.api.crateApiClientIdentityBackupEncode(secret: secret);

/// The secret from an identity backup file.
Uint8List identityBackupDecode({required String backup}) =>
    RustLib.instance.api.crateApiClientIdentityBackupDecode(backup: backup);

List<Server> serversList() => RustLib.instance.api.crateApiClientServersList();

/// Adds a server from an invite link or `host:port`, optionally claiming
/// ownership with the token the server printed on first start.
Future<AddServerOutcome> serverAdd({
  required String linkOrAddress,
  String? claimToken,
}) => RustLib.instance.api.crateApiClientServerAdd(
  linkOrAddress: linkOrAddress,
  claimToken: claimToken,
);

/// Pins a certificate after the user confirmed it.
void serverTrustFingerprint({
  required String address,
  required String fingerprint,
}) => RustLib.instance.api.crateApiClientServerTrustFingerprint(
  address: address,
  fingerprint: fingerprint,
);

/// Tries a server again now instead of waiting (or after a failure).
Future<void> serverRetryNow({required String serverKey}) =>
    RustLib.instance.api.crateApiClientServerRetryNow(serverKey: serverKey);

Future<void> serverRemove({required String serverKey}) =>
    RustLib.instance.api.crateApiClientServerRemove(serverKey: serverKey);

List<TrustedFingerprint> trustedFingerprints() =>
    RustLib.instance.api.crateApiClientTrustedFingerprints();

String? settingsGet({required String key}) =>
    RustLib.instance.api.crateApiClientSettingsGet(key: key);

/// `None` removes the setting.
void settingsSet({required String key, String? value}) =>
    RustLib.instance.api.crateApiClientSettingsSet(key: key, value: value);

Future<Message> sendMessage({
  required String serverKey,
  required PlatformInt64 channelId,
  required String content,
  required String nonce,
}) => RustLib.instance.api.crateApiClientSendMessage(
  serverKey: serverKey,
  channelId: channelId,
  content: content,
  nonce: nonce,
);

Future<Message> editMessage({
  required String serverKey,
  required PlatformInt64 messageId,
  required String content,
}) => RustLib.instance.api.crateApiClientEditMessage(
  serverKey: serverKey,
  messageId: messageId,
  content: content,
);

Future<void> deleteMessage({
  required String serverKey,
  required PlatformInt64 messageId,
}) => RustLib.instance.api.crateApiClientDeleteMessage(
  serverKey: serverKey,
  messageId: messageId,
);

/// Newest first; `before` pages backwards.
Future<List<Message>> fetchMessages({
  required String serverKey,
  required PlatformInt64 channelId,
  PlatformInt64? before,
  required int limit,
}) => RustLib.instance.api.crateApiClientFetchMessages(
  serverKey: serverKey,
  channelId: channelId,
  before: before,
  limit: limit,
);

Future<void> startTyping({
  required String serverKey,
  required PlatformInt64 channelId,
}) => RustLib.instance.api.crateApiClientStartTyping(
  serverKey: serverKey,
  channelId: channelId,
);

Future<Channel> createChannel({
  required String serverKey,
  required ChannelKind kind,
  required String name,
  String? topic,
  PlatformInt64? parentId,
}) => RustLib.instance.api.crateApiClientCreateChannel(
  serverKey: serverKey,
  kind: kind,
  name: name,
  topic: topic,
  parentId: parentId,
);

Future<Channel> updateChannel({
  required String serverKey,
  required PlatformInt64 channelId,
  required ChannelChanges changes,
}) => RustLib.instance.api.crateApiClientUpdateChannel(
  serverKey: serverKey,
  channelId: channelId,
  changes: changes,
);

Future<void> deleteChannel({
  required String serverKey,
  required PlatformInt64 channelId,
}) => RustLib.instance.api.crateApiClientDeleteChannel(
  serverKey: serverKey,
  channelId: channelId,
);

Future<void> reorderChannels({
  required String serverKey,
  required List<ChannelPosition> positions,
}) => RustLib.instance.api.crateApiClientReorderChannels(
  serverKey: serverKey,
  positions: positions,
);

Future<Channel> setChannelOverwrite({
  required String serverKey,
  required PlatformInt64 channelId,
  required PermissionOverwrite overwrite,
}) => RustLib.instance.api.crateApiClientSetChannelOverwrite(
  serverKey: serverKey,
  channelId: channelId,
  overwrite: overwrite,
);

Future<Channel> deleteChannelOverwrite({
  required String serverKey,
  required PlatformInt64 channelId,
  required OverwriteTargetKind targetKind,
  required PlatformInt64 targetId,
}) => RustLib.instance.api.crateApiClientDeleteChannelOverwrite(
  serverKey: serverKey,
  channelId: channelId,
  targetKind: targetKind,
  targetId: targetId,
);

Future<Role> createRole({
  required String serverKey,
  required String name,
  required int color,
  required PlatformInt64 permissions,
  required bool hoist,
  required bool mentionable,
}) => RustLib.instance.api.crateApiClientCreateRole(
  serverKey: serverKey,
  name: name,
  color: color,
  permissions: permissions,
  hoist: hoist,
  mentionable: mentionable,
);

Future<Role> updateRole({
  required String serverKey,
  required PlatformInt64 roleId,
  required RoleChanges changes,
}) => RustLib.instance.api.crateApiClientUpdateRole(
  serverKey: serverKey,
  roleId: roleId,
  changes: changes,
);

Future<void> deleteRole({
  required String serverKey,
  required PlatformInt64 roleId,
}) => RustLib.instance.api.crateApiClientDeleteRole(
  serverKey: serverKey,
  roleId: roleId,
);

/// The listed roles, lowest first, swap among the positions they hold.
Future<void> reorderRoles({
  required String serverKey,
  required Int64List roleIds,
}) => RustLib.instance.api.crateApiClientReorderRoles(
  serverKey: serverKey,
  roleIds: roleIds,
);

Future<Member> addMemberRole({
  required String serverKey,
  required PlatformInt64 userId,
  required PlatformInt64 roleId,
}) => RustLib.instance.api.crateApiClientAddMemberRole(
  serverKey: serverKey,
  userId: userId,
  roleId: roleId,
);

Future<Member> removeMemberRole({
  required String serverKey,
  required PlatformInt64 userId,
  required PlatformInt64 roleId,
}) => RustLib.instance.api.crateApiClientRemoveMemberRole(
  serverKey: serverKey,
  userId: userId,
  roleId: roleId,
);

Future<void> kickMember({
  required String serverKey,
  required PlatformInt64 userId,
  String? reason,
}) => RustLib.instance.api.crateApiClientKickMember(
  serverKey: serverKey,
  userId: userId,
  reason: reason,
);

Future<void> banMember({
  required String serverKey,
  required PlatformInt64 userId,
  String? reason,
}) => RustLib.instance.api.crateApiClientBanMember(
  serverKey: serverKey,
  userId: userId,
  reason: reason,
);

Future<void> unbanMember({
  required String serverKey,
  required PlatformInt64 userId,
}) => RustLib.instance.api.crateApiClientUnbanMember(
  serverKey: serverKey,
  userId: userId,
);

Future<List<Ban>> fetchBans({required String serverKey}) =>
    RustLib.instance.api.crateApiClientFetchBans(serverKey: serverKey);

/// `None` or empty clears the nickname.
Future<Member> updateNickname({
  required String serverKey,
  required PlatformInt64 userId,
  String? nickname,
}) => RustLib.instance.api.crateApiClientUpdateNickname(
  serverKey: serverKey,
  userId: userId,
  nickname: nickname,
);

Future<User> updateProfile({
  required String serverKey,
  required String displayName,
}) => RustLib.instance.api.crateApiClientUpdateProfile(
  serverKey: serverKey,
  displayName: displayName,
);

Future<void> updatePresence({
  required String serverKey,
  required PresenceStatus status,
}) => RustLib.instance.api.crateApiClientUpdatePresence(
  serverKey: serverKey,
  status: status,
);

Future<Invite> createInvite({
  required String serverKey,
  int? maxUses,
  int? expiresInS,
}) => RustLib.instance.api.crateApiClientCreateInvite(
  serverKey: serverKey,
  maxUses: maxUses,
  expiresInS: expiresInS,
);

Future<List<Invite>> fetchInvites({required String serverKey}) =>
    RustLib.instance.api.crateApiClientFetchInvites(serverKey: serverKey);

Future<void> revokeInvite({required String serverKey, required String code}) =>
    RustLib.instance.api.crateApiClientRevokeInvite(
      serverKey: serverKey,
      code: code,
    );

Future<ServerInfo> updateServer({
  required String serverKey,
  required ServerChanges changes,
}) => RustLib.instance.api.crateApiClientUpdateServer(
  serverKey: serverKey,
  changes: changes,
);
