// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Version of the client core and the gateway protocol it speaks,
/// e.g. `0.1.0 (protocol v1)`.
String coreVersion() => RustLib.instance.api.crateApiSystemCoreVersion();
