// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

@freezed
sealed class AddServerOutcome with _$AddServerOutcome {
  const AddServerOutcome._();

  const factory AddServerOutcome.added(Server field0) = AddServerOutcome_Added;

  /// The certificate is not pinned and not from a public authority. Ask
  /// the user, then call `server_trust_fingerprint` and add again.
  const factory AddServerOutcome.needsTrust({
    required String address,
    required String fingerprint,
  }) = AddServerOutcome_NeedsTrust;
}

class Ban {
  final User user;
  final String? reason;
  final PlatformInt64? bannedBy;
  final PlatformInt64 createdAtMs;

  const Ban({
    required this.user,
    this.reason,
    this.bannedBy,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      user.hashCode ^
      reason.hashCode ^
      bannedBy.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Ban &&
          runtimeType == other.runtimeType &&
          user == other.user &&
          reason == other.reason &&
          bannedBy == other.bannedBy &&
          createdAtMs == other.createdAtMs;
}

class Channel {
  final PlatformInt64 id;
  final ChannelKind kind;
  final String name;
  final String? topic;
  final PlatformInt64? parentId;
  final int position;
  final List<PermissionOverwrite> overwrites;

  const Channel({
    required this.id,
    required this.kind,
    required this.name,
    this.topic,
    this.parentId,
    required this.position,
    required this.overwrites,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      name.hashCode ^
      topic.hashCode ^
      parentId.hashCode ^
      position.hashCode ^
      overwrites.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Channel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          name == other.name &&
          topic == other.topic &&
          parentId == other.parentId &&
          position == other.position &&
          overwrites == other.overwrites;
}

/// Absent fields stay unchanged. An empty topic clears it; `parent_id` 0
/// moves the channel out of its category.
class ChannelChanges {
  final String? name;
  final String? topic;
  final PlatformInt64? parentId;

  const ChannelChanges({this.name, this.topic, this.parentId});

  static Future<ChannelChanges> default_() =>
      RustLib.instance.api.crateApiTypesChannelChangesDefault();

  @override
  int get hashCode => name.hashCode ^ topic.hashCode ^ parentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelChanges &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          topic == other.topic &&
          parentId == other.parentId;
}

enum ChannelKind { text, voice, category }

class ChannelPermissions {
  final PlatformInt64 channelId;
  final PlatformInt64 permissions;

  const ChannelPermissions({
    required this.channelId,
    required this.permissions,
  });

  @override
  int get hashCode => channelId.hashCode ^ permissions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelPermissions &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          permissions == other.permissions;
}

class ChannelPosition {
  final PlatformInt64 channelId;
  final int position;

  const ChannelPosition({required this.channelId, required this.position});

  @override
  int get hashCode => channelId.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelPosition &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          position == other.position;
}

@freezed
sealed class ConnectionState with _$ConnectionState {
  const ConnectionState._();

  const factory ConnectionState.connecting() = ConnectionState_Connecting;
  const factory ConnectionState.connected() = ConnectionState_Connected;
  const factory ConnectionState.reconnecting({
    required int attempt,
    required int retryInMs,
  }) = ConnectionState_Reconnecting;

  /// No more retries; the user has to act.
  const factory ConnectionState.failed({
    required FailureReason reason,
    required String message,

    /// With `FingerprintChanged`: the pinned fingerprint (when there is
    /// one) and the one the server showed instead, as lowercase hex.
    String? expectedFingerprint,
    String? presentedFingerprint,
  }) = ConnectionState_Failed;
}

@freezed
sealed class CoreError with _$CoreError implements FrbException {
  const CoreError._();

  const factory CoreError.notInitialized() = CoreError_NotInitialized;
  const factory CoreError.noIdentity() = CoreError_NoIdentity;
  const factory CoreError.unknownServer() = CoreError_UnknownServer;
  const factory CoreError.notConnected() = CoreError_NotConnected;
  const factory CoreError.timeout() = CoreError_Timeout;
  const factory CoreError.invalidInput({required String message}) =
      CoreError_InvalidInput;
  const factory CoreError.server({
    required ErrorCode code,
    required String message,
    int? retryAfterMs,
  }) = CoreError_Server;
  const factory CoreError.fingerprintMismatch({
    required String expected,
    required String presented,
  }) = CoreError_FingerprintMismatch;
  const factory CoreError.rejected({
    required FailureReason reason,
    required String message,
  }) = CoreError_Rejected;
  const factory CoreError.connection({required String message}) =
      CoreError_Connection;
  const factory CoreError.storage({required String message}) =
      CoreError_Storage;
}

class CoreEvent {
  final String serverKey;
  final CoreEventPayload payload;

  const CoreEvent({required this.serverKey, required this.payload});

  @override
  int get hashCode => serverKey.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreEvent &&
          runtimeType == other.runtimeType &&
          serverKey == other.serverKey &&
          payload == other.payload;
}

@freezed
sealed class CoreEventPayload with _$CoreEventPayload {
  const CoreEventPayload._();

  const factory CoreEventPayload.connectionState(ConnectionState field0) =
      CoreEventPayload_ConnectionState;

  /// After every fresh handshake; replaces all state for the server.
  const factory CoreEventPayload.ready(ReadySnapshot field0) =
      CoreEventPayload_Ready;
  const factory CoreEventPayload.messageCreate(Message field0) =
      CoreEventPayload_MessageCreate;
  const factory CoreEventPayload.messageUpdate(Message field0) =
      CoreEventPayload_MessageUpdate;
  const factory CoreEventPayload.messageDelete({
    required PlatformInt64 channelId,
    required PlatformInt64 messageId,
  }) = CoreEventPayload_MessageDelete;
  const factory CoreEventPayload.channelCreate(Channel field0) =
      CoreEventPayload_ChannelCreate;
  const factory CoreEventPayload.channelUpdate(Channel field0) =
      CoreEventPayload_ChannelUpdate;
  const factory CoreEventPayload.channelDelete({
    required PlatformInt64 channelId,
  }) = CoreEventPayload_ChannelDelete;
  const factory CoreEventPayload.roleCreate(Role field0) =
      CoreEventPayload_RoleCreate;
  const factory CoreEventPayload.roleUpdate(Role field0) =
      CoreEventPayload_RoleUpdate;
  const factory CoreEventPayload.roleDelete({required PlatformInt64 roleId}) =
      CoreEventPayload_RoleDelete;
  const factory CoreEventPayload.memberJoin(Member field0) =
      CoreEventPayload_MemberJoin;
  const factory CoreEventPayload.memberLeave({required PlatformInt64 userId}) =
      CoreEventPayload_MemberLeave;
  const factory CoreEventPayload.memberUpdate(Member field0) =
      CoreEventPayload_MemberUpdate;
  const factory CoreEventPayload.presenceUpdate(Presence field0) =
      CoreEventPayload_PresenceUpdate;
  const factory CoreEventPayload.typingStart({
    required PlatformInt64 channelId,
    required PlatformInt64 userId,
  }) = CoreEventPayload_TypingStart;
  const factory CoreEventPayload.serverUpdate(ServerInfo field0) =
      CoreEventPayload_ServerUpdate;

  /// The user's own permissions changed.
  const factory CoreEventPayload.permissionsUpdate({
    required PlatformInt64 serverPermissions,
    required List<ChannelPermissions> channelPermissions,
  }) = CoreEventPayload_PermissionsUpdate;
}

enum ErrorCode {
  unauthorized,
  forbidden,
  notFound,
  invalidArgument,
  rateLimited,
  invalidSession,
  conflict,
  internal,
  unknown,
}

enum FailureReason {
  /// The server refused this identity: not a member, a bad invite or
  /// claim token, or banned before connecting.
  rejected,
  kicked,
  banned,

  /// The certificate no longer matches the pinned fingerprint.
  fingerprintChanged,

  /// The server speaks a different protocol version.
  incompatible,
}

class GeneratedIdentity {
  /// Keep in secure storage; it is the identity.
  final Uint8List secret;
  final IdentityInfo info;

  const GeneratedIdentity({required this.secret, required this.info});

  @override
  int get hashCode => secret.hashCode ^ info.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneratedIdentity &&
          runtimeType == other.runtimeType &&
          secret == other.secret &&
          info == other.info;
}

/// A key pair's public half, ready to show.
class IdentityInfo {
  final String publicKeyHex;

  /// Short form like `ABCD-EFGH-IJKL-MNOP`.
  final String fingerprint;

  const IdentityInfo({required this.publicKeyHex, required this.fingerprint});

  @override
  int get hashCode => publicKeyHex.hashCode ^ fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityInfo &&
          runtimeType == other.runtimeType &&
          publicKeyHex == other.publicKeyHex &&
          fingerprint == other.fingerprint;
}

class Invite {
  final String code;

  /// `opencord://host:port/invite/CODE#fp=...`, ready to share.
  final String link;
  final PlatformInt64? createdBy;
  final PlatformInt64 createdAtMs;
  final int? maxUses;
  final int uses;
  final PlatformInt64? expiresAtMs;

  const Invite({
    required this.code,
    required this.link,
    this.createdBy,
    required this.createdAtMs,
    this.maxUses,
    required this.uses,
    this.expiresAtMs,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      link.hashCode ^
      createdBy.hashCode ^
      createdAtMs.hashCode ^
      maxUses.hashCode ^
      uses.hashCode ^
      expiresAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Invite &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          link == other.link &&
          createdBy == other.createdBy &&
          createdAtMs == other.createdAtMs &&
          maxUses == other.maxUses &&
          uses == other.uses &&
          expiresAtMs == other.expiresAtMs;
}

class Member {
  final User user;
  final String? nickname;

  /// Without @everyone.
  final Int64List roleIds;
  final PlatformInt64 joinedAtMs;

  const Member({
    required this.user,
    this.nickname,
    required this.roleIds,
    required this.joinedAtMs,
  });

  @override
  int get hashCode =>
      user.hashCode ^
      nickname.hashCode ^
      roleIds.hashCode ^
      joinedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Member &&
          runtimeType == other.runtimeType &&
          user == other.user &&
          nickname == other.nickname &&
          roleIds == other.roleIds &&
          joinedAtMs == other.joinedAtMs;
}

class Message {
  final PlatformInt64 id;
  final PlatformInt64 channelId;
  final PlatformInt64 authorId;
  final String content;
  final PlatformInt64 createdAtMs;
  final PlatformInt64? editedAtMs;

  /// Set on messages this client sent, to match pending ones.
  final String? nonce;

  const Message({
    required this.id,
    required this.channelId,
    required this.authorId,
    required this.content,
    required this.createdAtMs,
    this.editedAtMs,
    this.nonce,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      channelId.hashCode ^
      authorId.hashCode ^
      content.hashCode ^
      createdAtMs.hashCode ^
      editedAtMs.hashCode ^
      nonce.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          channelId == other.channelId &&
          authorId == other.authorId &&
          content == other.content &&
          createdAtMs == other.createdAtMs &&
          editedAtMs == other.editedAtMs &&
          nonce == other.nonce;
}

enum OverwriteTargetKind { role, member }

class PermissionOverwrite {
  final OverwriteTargetKind targetKind;
  final PlatformInt64 targetId;
  final PlatformInt64 allow;
  final PlatformInt64 deny;

  const PermissionOverwrite({
    required this.targetKind,
    required this.targetId,
    required this.allow,
    required this.deny,
  });

  @override
  int get hashCode =>
      targetKind.hashCode ^ targetId.hashCode ^ allow.hashCode ^ deny.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PermissionOverwrite &&
          runtimeType == other.runtimeType &&
          targetKind == other.targetKind &&
          targetId == other.targetId &&
          allow == other.allow &&
          deny == other.deny;
}

class Presence {
  final PlatformInt64 userId;
  final PresenceStatus status;

  const Presence({required this.userId, required this.status});

  @override
  int get hashCode => userId.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Presence &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          status == other.status;
}

enum PresenceStatus { online, idle, dnd, offline }

/// Everything about a server right after connecting.
class ReadySnapshot {
  final User selfUser;
  final ServerInfo server;

  /// Only channels this user can view.
  final List<Channel> channels;
  final List<Role> roles;
  final List<Member> members;
  final List<Presence> presences;
  final PlatformInt64 serverPermissions;
  final List<ChannelPermissions> channelPermissions;

  const ReadySnapshot({
    required this.selfUser,
    required this.server,
    required this.channels,
    required this.roles,
    required this.members,
    required this.presences,
    required this.serverPermissions,
    required this.channelPermissions,
  });

  @override
  int get hashCode =>
      selfUser.hashCode ^
      server.hashCode ^
      channels.hashCode ^
      roles.hashCode ^
      members.hashCode ^
      presences.hashCode ^
      serverPermissions.hashCode ^
      channelPermissions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadySnapshot &&
          runtimeType == other.runtimeType &&
          selfUser == other.selfUser &&
          server == other.server &&
          channels == other.channels &&
          roles == other.roles &&
          members == other.members &&
          presences == other.presences &&
          serverPermissions == other.serverPermissions &&
          channelPermissions == other.channelPermissions;
}

class Role {
  final PlatformInt64 id;
  final String name;

  /// 0xRRGGBB; 0 means no color.
  final int color;
  final int position;
  final PlatformInt64 permissions;
  final bool hoist;
  final bool mentionable;

  const Role({
    required this.id,
    required this.name,
    required this.color,
    required this.position,
    required this.permissions,
    required this.hoist,
    required this.mentionable,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      color.hashCode ^
      position.hashCode ^
      permissions.hashCode ^
      hoist.hashCode ^
      mentionable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Role &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          color == other.color &&
          position == other.position &&
          permissions == other.permissions &&
          hoist == other.hoist &&
          mentionable == other.mentionable;
}

class RoleChanges {
  final String? name;
  final int? color;
  final PlatformInt64? permissions;
  final bool? hoist;
  final bool? mentionable;

  const RoleChanges({
    this.name,
    this.color,
    this.permissions,
    this.hoist,
    this.mentionable,
  });

  static Future<RoleChanges> default_() =>
      RustLib.instance.api.crateApiTypesRoleChangesDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      color.hashCode ^
      permissions.hashCode ^
      hoist.hashCode ^
      mentionable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoleChanges &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          color == other.color &&
          permissions == other.permissions &&
          hoist == other.hoist &&
          mentionable == other.mentionable;
}

/// A server in the local list.
class Server {
  /// `host:port`; identifies the server in every other call.
  final String key;
  final String name;
  final String host;
  final int port;
  final PlatformInt64? userId;

  /// Pinned certificate fingerprint (lowercase hex), if any.
  final String? fingerprint;

  const Server({
    required this.key,
    required this.name,
    required this.host,
    required this.port,
    this.userId,
    this.fingerprint,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      userId.hashCode ^
      fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Server &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          userId == other.userId &&
          fingerprint == other.fingerprint;
}

class ServerChanges {
  final String? name;
  final String? description;
  final bool? openJoin;

  const ServerChanges({this.name, this.description, this.openJoin});

  static Future<ServerChanges> default_() =>
      RustLib.instance.api.crateApiTypesServerChangesDefault();

  @override
  int get hashCode => name.hashCode ^ description.hashCode ^ openJoin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerChanges &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          openJoin == other.openJoin;
}

class ServerInfo {
  final String serverIdHex;
  final String name;
  final String description;
  final PlatformInt64? ownerId;
  final bool openJoin;
  final PlatformInt64 everyoneRoleId;

  const ServerInfo({
    required this.serverIdHex,
    required this.name,
    required this.description,
    this.ownerId,
    required this.openJoin,
    required this.everyoneRoleId,
  });

  @override
  int get hashCode =>
      serverIdHex.hashCode ^
      name.hashCode ^
      description.hashCode ^
      ownerId.hashCode ^
      openJoin.hashCode ^
      everyoneRoleId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerInfo &&
          runtimeType == other.runtimeType &&
          serverIdHex == other.serverIdHex &&
          name == other.name &&
          description == other.description &&
          ownerId == other.ownerId &&
          openJoin == other.openJoin &&
          everyoneRoleId == other.everyoneRoleId;
}

/// A pinned certificate.
class TrustedFingerprint {
  /// `host:port`.
  final String address;

  /// Lowercase hex SHA-256.
  final String fingerprint;

  const TrustedFingerprint({required this.address, required this.fingerprint});

  @override
  int get hashCode => address.hashCode ^ fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrustedFingerprint &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          fingerprint == other.fingerprint;
}

class User {
  final PlatformInt64 id;
  final String publicKeyHex;
  final String fingerprint;
  final String displayName;

  const User({
    required this.id,
    required this.publicKeyHex,
    required this.fingerprint,
    required this.displayName,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      publicKeyHex.hashCode ^
      fingerprint.hashCode ^
      displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          publicKeyHex == other.publicKeyHex &&
          fingerprint == other.fingerprint &&
          displayName == other.displayName;
}
