[package]
name = "opencord-server"
description = "Self-hostable Opencord community server."
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "AGPL-3.0-or-later"
publish = false

[dependencies]
anyhow.workspace = true
axum.workspace = true
axum-server.workspace = true
bytes.workspace = true
clap.workspace = true
futures-util.workspace = true
getrandom.workspace = true
governor.workspace = true
hex.workspace = true
rcgen.workspace = true
rustls.workspace = true
serde.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
toml.workspace = true
opencord-common.workspace = true
opencord-proto.workspace = true
prost.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio-rustls.workspace = true
tokio-tungstenite.workspace = true
