// Rebuilds the emoji list for the picker, the reaction pill and the `:`
// autocomplete from iamcal/emoji-data (MIT). Run from app/:
//
//   dart run tool/build_emoji.dart
//
// The upstream JSON (1.3 MB) is downloaded once into .dart_tool/. Skin tone
// components and obsoleted entries are left out, and so are emoji newer
// than [maxVersion], which not every system emoji font can draw yet.

import 'dart:convert';
import 'dart:io';

/// iamcal/emoji-data commit (tag v16.0.0) the list is taken from.
const upstreamCommit = '2771d0b1b3af25c069086e68e38f901c3dda8bdf';

/// The newest Unicode emoji version kept.
const maxVersion = 15.0;

const dartOutput = 'lib/ui/emoji/emoji_data.dart';
const licenseOutput = 'assets/licenses/emoji-data-MIT.txt';

/// Upstream category → `EmojiCategory` value.
const categories = {
  'Smileys & Emotion': 'smileys',
  'People & Body': 'people',
  'Animals & Nature': 'nature',
  'Food & Drink': 'food',
  'Activities': 'activities',
  'Travel & Places': 'travel',
  'Objects': 'objects',
  'Symbols': 'symbols',
  'Flags': 'flags',
};

Future<void> main() async {
  final cache = Directory('.dart_tool/emoji_data/$upstreamCommit');
  await cache.create(recursive: true);
  final json = await download('emoji.json', cache);
  final license = await download('LICENSE', cache);

  final entries =
      (jsonDecode(await json.readAsString()) as List)
          .cast<Map<String, Object?>>()
          .where(
            (entry) =>
                categories.containsKey(entry['category']) &&
                entry['obsoleted_by'] == null &&
                double.parse(entry['added_in']! as String) <= maxVersion,
          )
          .toList()
        ..sort(
          (a, b) =>
              (a['sort_order']! as int).compareTo(b['sort_order']! as int),
        );

  final lines = [
    for (final entry in entries)
      "  Emoji('${escape(entry['unified']! as String)}', "
          "${quote(name(entry))}, "
          "[${(entry['short_names']! as List).cast<String>().map(quote).join(', ')}], "
          'EmojiCategory.${categories[entry['category']]}),',
  ];
  await File(dartOutput).writeAsString('''
// GENERATED by tool/build_emoji.dart from iamcal/emoji-data
// ($upstreamCommit, MIT). Rerun it to update.

import 'package:opencord/ui/emoji/emoji.dart';

/// Every emoji the picker offers, in Unicode's order.
const emojiData = <Emoji>[
${lines.join('\n')}
];
''');
  await Process.run(Platform.resolvedExecutable, ['format', dartOutput]);
  await license.copy(licenseOutput);
  stdout.writeln('${entries.length} emoji written to $dartOutput');
}

/// `1F44D` or `2764-FE0F` → `\u{1F44D}` or `\u{2764}\u{FE0F}`.
String escape(String unified) =>
    unified.split('-').map((code) => '\\u{$code}').join();

/// "THUMBS UP SIGN" → "thumbs up sign"; flags and a few others have no
/// name upstream, so their first short name stands in.
String name(Map<String, Object?> entry) {
  final name = entry['name'] as String?;
  if (name == null || name.isEmpty) {
    return (entry['short_name']! as String).replaceAll('_', ' ');
  }
  return name.toLowerCase();
}

String quote(String text) =>
    "'${text.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

Future<File> download(String name, Directory cache) async {
  final file = File('${cache.path}/$name');
  if (await file.exists()) return file;
  final url = Uri.https(
    'raw.githubusercontent.com',
    '/iamcal/emoji-data/$upstreamCommit/$name',
  );
  final client = HttpClient();
  try {
    final response = await (await client.getUrl(url)).close();
    if (response.statusCode != 200) {
      throw HttpException('HTTP ${response.statusCode}', uri: url);
    }
    await response.pipe(file.openWrite());
  } finally {
    client.close();
  }
  return file;
}
